name:
  Cron Job

on:
  # Triggers the workflow every day at 12am
  schedule:
    - cron: "0 0 * * *"
  # Ability to run manually  
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
 
jobs:
  update:

    runs-on: ubuntu-latest
    env:
      PRODUCT_HUNT_DEVELOPER_TOKEN: ${{ secrets.PRODUCT_HUNT_DEVELOPER_TOKEN }}
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      AIRTABLE_BASE_ID:  ${{ secrets.AIRTABLE_BASE_ID }}
      AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }}
 
    steps:
    # Downloads repo
      - name: Checkout
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
          persist-credentials: false
    # Inits repo and runs script
      - name: Init
        run: npm install && npx tsc --outDir src/bin && npx nodemon ./src/server.ts
      - name: Hit endpoint
        run: curl http://localhost:4000/updateProducts
        
          
